version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./platform_back_end:/platform_back_end
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    container_name: django
    build: .
    restart: always
    command: bash -c "
      python3 manage.py collectstatic --no-input &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn platform_back_end.wsgi:application -b 0:80"
    volumes:
      - ./platform_back_end:/platform_back_end

  app:
    container_name: ks-platform-front
    build: 
      context: ./ks-platform-front
      dockerfile: Dockerfile
    volumes:
      - "./ks-platform-front:/app"
      - "/app/node_modules"
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development