version: '3'
services:
  nginx:
    container_name: nginx
    nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./platform_back_end:/platform_back_end
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    container_name: django
    build: .
    restart: always
    command: bash -c "
      python3 manage.py collectstatic --no-input &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn platform_back_end.wsgi:application -b 0:80"
    volumes:
      - ./platform_back_end:/platform_back_end