version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: ks-platform/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./platform_back_end:/srv/KnowledgeSharingPlatform
      - ./log:/var/log/nginx
    depends_on:
      - django

  django:
    container_name: django
    build: ./platform_back_end
    image: ks-platform/django
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./platform_back_end:/srv/KnowledgeSharingPlatform
      - ./log:/var/log/uwsgi