version: '3'
networks:
  knowledge-sharing-platform:
    ipam:
      config:
        - subnet: 192.168.1.0/24
volumes:
  nginx-volume: {}
  web-volume: {}
  cache-volume: {}
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./platform_back_end:/platform_back_end
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      knowledge-sharing-platform:
        ipv4_address: 192.168.1.2

  web:
    container_name: django
    build: .
    restart: always
    command: bash -c "
      python3 manage.py collectstatic --no-input &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn platform_back_end.wsgi:application -b 0:80"
    volumes:
      - ./platform_back_end:/platform_back_end
    networks:
      knowledge-sharing-platform:
        ipv4_address: 192.168.1.3

  cache:
    image: redis:5.0.3
    command: redis-server --requirepass samplepassword
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - cache-volume:/data
    networks:
      knowledge-sharing-platform:
        ipv4_address: 192.168.1.4