# Generated by Django 3.2.9 on 2021-11-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('nickname', models.CharField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(default='USER', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.CharField(default=None, max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
