# Generated by Django 3.2.9 on 2021-11-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('post_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=255, null=True)),
                ('contents', models.TextField(null=True)),
                ('comments', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('update_count', models.IntegerField(default=0)),
                ('is_secret', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=150)),
                ('post_id', models.CharField(default=None, max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, null=True)),
                ('post_id', models.CharField(max_length=255)),
            ],
        ),
    ]
