# Generated by Django 3.2.9 on 2021-11-29 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_auto_20211129_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 23, 56, 23, 398739)),
        ),
    ]
